version: "3.8"

services:
  node:
    build: .
    image: node-propagation
    environment:
      - STRATEGY=multicast   # gossip, broadcast, multicast, singlecast
      - PACKET_LOSS_PROBABILITY=0
      - NODE_BROKEN_PROBABILITY=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/multicast-healthy:/logs
    networks:
      node-net:
        aliases:
          - node

networks:
  node-net: